### PR TITLE
Treat zero as a valid input value

### LINKED ISSUE #52: Input defined as `type: 'number'` doesn't accept the value 0
In a form view created by the CLI, I have added `type: 'number'` (`ExtendedInput` is the same as from the demo app):

```
            new ExtendedInput({
                label: "Order",
                name: "order",
                value: this.model && this.model.order,
                type: 'number',
                required: true,
                placeholder: "Order",
                parent: this
            })
```

The model's property is defined as such:

```
        order: ['number', true, 100]
```

The form displays nice little up and down arrow, and using the keyboard arrows changes the values appropriately.
Positive and negative values work fine, however when passing from -1 to 0, or from 1 to 0 the error message `This field is required.` is displayed.

It should be possible to enter a number with a value of 0.

### PR DESCRIPTION
**Pull request by kamilogorek**
Fixes #52

### CODE REVIEW

**Comment by StephanHoyer** [comment]
please merge this!

**Comment by kamilogorek** [comment]
@AmpersandJS/core-team

**Comment by kamilogorek** [comment]
@cdaringe

**Comment by cdaringe** [comment]
overall looks good.  does this similarly warrant an update to: https://github.com/AmpersandJS/ampersand-input-view/blob/treat-zero-as-valid/ampersand-input-view.js#L180
i.e.  `if (this.inputValue !== '' && this.changed) {`

**Comment by wraithgar** [comment]
+1

**Comment by lukekarrys** [comment]
+1

**Comment by wraithgar** [comment]
Patch release
Shipped as v4.0.2

**Pull request merged**
