### PR TITLE
Add readonly option

### PR DESCRIPTION
**Pull request by doratias**

### CODE REVIEW

**Comment by cdaringe** [comment]
Hey @doratias, looks good.  Willing to do a README update and a test?

**Comment by doratias** [comment]
@cdaringe tnx, done.

**Comment by cdaringe** [comment]
rad+! +1

**Comment by fyockm** [comment]
LGTM +1

**Comment by cdaringe** [comment]
yeehaw.  i don't have publish access, but this will go into the next release

**Comment by wraithgar** [comment]
@cdaringe you have npm access now. Go ahead and throw the scripts into package.json from checkbox-view and go hog wild. https://github.com/AmpersandJS/ampersand-checkbox-view/blob/master/package.json#L47-L50

**Comment by cdaringe** [comment]
@wraithgar.  guten tag!
eek!
```bash
npm ERR! You do not have permission to publish 'ampersand-select-view'. Are you logged in as the correct user? : ampersand-select-view

cdieringer@Snapper-osx:~/node/release/ampersand-select-view$ npm whoami
cdaringe

```

**Comment by wraithgar** [comment]
I think I added you to input-view instead.  Just added you to select-view.  Doesn't show up on npmjs yet but that could be a caching issue.

```gar@Iceman ~/D/a/select-view (master)> npm owner ls ampersand-select-view 
henrikjoreteg <henrik@andyet.net>
latentflip <phil@latentflip.com>
lukekarrys <luke@lukekarrys.com>
gar <gar+npm@danger.computer>
andyet <ops@andyet.net>
cdaringe <cdaringe@gmail.com>```

**Comment by cdaringe** [comment]
whoa-hoa! looks like it staged my failed attempts and still ran them.  that's not great.  i ran it a total of 3 times, two failed ~hour ago, third succeeded ~now, yet it still pushed 3 minor versions.  it's no big deal, but 'empty' history.  Thanks gar

**Comment by wraithgar** [comment]
Ah yes we may need to consider a bailout option at the end (all the && stuff) || (bail out)

**Comment by wraithgar** [comment]
Or a forced reset to origin/master after the pull

**Pull request merged**
