### PR TITLE
Added tabindex as a new option.

### PR DESCRIPTION
**Pull request by kylefarris**
I found a need to change the tab order of my fields. This very simple addition will allow for that. I am about to submit a PR for `ampersand-select-view` to include this as well.

### CODE REVIEW

**Comment by cdaringe** [comment]
looks ok to me.

each control getting a default tab index of 0 may be breaking (UX-wise) for some users.  because of this, i would suppose this gets a major.  thoughts?

further, i'm unsure how different browsers would handle duplicate index values.  i would guess that in-order depth traversal would yield the tab ordering when there are conflicts

**Comment by cdaringe** [comment]
would you add a bit to the changelog section in the bottom of the README about this, after we sync up on proper version bump & index conflicts?

**Comment by wraithgar** [comment]
Could tabindex be an attribute that does not default?  That would prevent it from showing up now by default where people aren't expecting it, and also prevent them all from being `0` if not specified.  At least I _think_ that's what removing the `true, 0` would do.

**Comment by kylefarris** [comment]
Tabindex being 0 is the browser default anyways... see here: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex . If 0, the indexing defaults to the browser default (usually the natural order of the elements on the page).

**Comment by wraithgar** [comment]
Hey that's great thank you.  One could argue this is now a minor.

**Comment by kylefarris** [comment]
Definitely a non-breaking feature enhancement minor release.

**Comment by cdaringe** [comment]
thanks all, +1

**Comment by wraithgar** [comment]
+1 from me also, thanks also for cleaning up the readme whitespace etc

**Comment by kylefarris** [comment]
Haha, I won't take too much credit for that. I have a beautifier plugin for Jade, MD, JS, CSS, and a couple other things active in my instance of Atom at work. It took the liberty of making it more "beautiful" for you. :-)

**Comment by cdaringe** [comment]
updated published as 5.0.1

**Comment by wraithgar** [comment]
Should that have been 5.1.0?

**Comment by cdaringe** [comment]
yeeep. bumped to 5.1.0 WITH `changelog` update.  deprecated `5.0.1` w/ note to use 5.0.0 or 5.1.0, _just_ to be thorough

**Pull request merged**
